### ISSUE TITLE
Feature: Persist search pattern

### ISSUE THREAD

**Issue by ineu** [geksilla/atom-fuzzy-grep#15]
In built-in Atom's fuzy-finder there's an option called 'Preserve last search'. As fuzzy-finder is not capable of opening multiple files at once, this option can be handy to go though all matches one by one. It would be nice to have the same feature in fuzzy-grep, so user won't need to fall back to `ctrl-shift-f` when he expects multiple matches.

**Comment by geksilla** [comment]
@ineu make sense. What about by hitting <kbd>Tab</kbd> open file to preview in new tab, repeatedly <kbd>Tab</kbd> hits will change source for opened tab based on selected item.
<kbd>Alt</kbd>+<kbd>Enter</kbd> to persist file in new tab. Thanks.

**Comment by ineu** [comment]
So alt+enter opens file, keeping grep dialog open? Sounds fine.
Still it would be fine to save/restore search string, as it may be desirable to open some files, close dialog and after some work reopen it with the same search string.

**Comment by geksilla** [comment]
@ineu both described scenarios will keep grep dialog opened. As quick fix I can implement, or if you want send PR, opening dialog with last searched string.

**Comment by ineu** [comment]
Ok, will try to implement this thing. Good occasion to learn something about Atom plugins )

**Comment by geksilla** [comment]
@ineu, I've commited first part of the feature. Few things there:
- New option **Preserve Last Search** if you want to always use last search string.
- New method to open dialog with last search string entered. You can bind this method in your _keymap.json_ file, for example:

```
'atom-workspace':
  'ctrl-alt-shift-g': 'fuzzy-grep:toggleLastSearch'
```

Or check **Preserve Last Search** option in package Settings.

You can try new changes by clone this repo and link it your packages. Thanks.

**Comment by geksilla** [comment]
@ineu, released new version with this feature. You can update the package.
I leave this issue opened. Will track preview and cycle opening features here.

**Comment by ineu** [comment]
@geksilla Works great, thank you

**Comment by geksilla** [comment]
@ineu, yw. thanks for great request!
