### ISSUE TITLE
Failed to spawn command `ag` on second window

### ISSUE THREAD

**Issue by tuananh** [geksilla/atom-fuzzy-grep#16]
When i open another folder with `atom .`, it complains that it cannot find `ag` in `PATH`.

```
Failed to spawn command
```

**Comment by geksilla** [comment]
Hi @tuananh, sorry for late response. Did you install ag and what OS you use?

**Comment by tuananh** [comment]
@geksilla i installed `ag` and it works just fine if i have 1 Atom window. Sometimes when I open another window (via `atom` cli), i got that error on the second window. The first window still works just fine.

I'm using latest Atom (1.0.2) and OS X (10.11)

**Comment by mendeza** [comment]
For me it doesn't work at all with `ag`, and it makes no difference if there are zero, one, or more than one buffers.

```
Uncaught BufferedProcessError: Failed to spawn command `ag`. Make sure `ag` is installed and on your PATH
```

`ag` was installed with homebrew and symlinked to Cellar as per usual.

```
ls -la /usr/local/bin
lrwxr-xr-x   1 XXXXXXX  admin    43B Sep  7 17:27 ag@ -> ../Cellar/the_silver_searcher/0.30.0/bin/ag
```

so `ag` is definitely in the Path...

```
$ which ag
/usr/local/bin/ag
```

Using OS X 10.10.5 and Atom 1.0.11.

**Comment by jamby** [comment]
I'm in the same boat as @mendeza here. I have `ag` installed and am running OS X 10.10.3 with Atom 1.0.11, and it still is giving me the error of `Failed to spawn command 'ag'`.

**Comment by geksilla** [comment]
Seems like issue with _PATH_ settings in atom. Currently running on Linux Ubuntu 14.04, atom 1.0.11 and cannot reproduce this. Will check this on mac as well. Can you please try possible workarounds:
- launch atom from terminal
- or set _Grep Command String_ with absolute path to _ag_

I've seen similar issues with another packages when ran atom from spotlight/alfred.
Thanks.

**Comment by geksilla** [comment]
Possible related [issue](https://github.com/atom/atom/issues/3018)

**Comment by AshCoolman** [comment]
@geksilla yeah, found a solution that worked for me: [open using `atom` from terminal](https://github.com/atom/atom/issues/3018#issuecomment-98485227)

@irjamby @mendeza  @tuananh

**Comment by jamby** [comment]
I wrote a ruby script to fix this immediately, since it needs to be redone every time Atom updates if anyone else comes across this:

https://github.com/jamby/AtomGrepFix

Just remember to make sure your path is correct!

**Comment by geksilla** [comment]
@jamby, this is awesome! In the one of the project which I contributed we hot fix $PATH variable on package activation. Also there is a package [environment](https://atom.io/packages/environment) that can fix this problem but I don't use it since it works for OS X only. May be I will write another package that could fix env variables when atom launched not from terminal. Or provide code snippet in README that you can use in your `init.coffee` to fix PATH problems.

**Comment by jamby** [comment]
@geksilla If you know what I need to put inside the `init.coffee` to fix it for when atom isn't launched from terminal, let me know. I'll update the script to question what you want to do exactly (either for terminal or not for terminal).

**Comment by geksilla** [comment]
So I will use [environment](https://atom.io/packages/environment) to fix this on OS X. Currently commited required changes and info to README. Let me check it on my Mac. I will publish new version after testing.

**Comment by geksilla** [comment]
Released new version. Please update your package and install [environment](https://atom.io/packages/environment) package if not installed.

**Comment by jamby** [comment]
@geksilla This is now happening in the latest build of Atom (1.6.2).

**Comment by liuderchi** [comment]
@geksilla This is now happening in the build of Atom v1.8.0.

**Comment by mgwio** [comment]
@liuderchi The functionality of the environment package was added to [atom natively](https://github.com/atom-community/environment):

> This package is a no-op on Atom >= 1.7.0. It uses functionality built into Atom in 1.7.0+ and allows for that to function in prior versions of Atom.

Removing the environment package fixed this for me.
