### ISSUE TITLE
Settings not showing correctly.

### ISSUE THREAD

**Issue by jackcasey** [geksilla/atom-fuzzy-grep#27]
Since upgrading to 0.11 My settings section of the plugin only shows the one setting I already set to non-default:

![screen shot 2016-01-22 at 2 14 01 pm](https://cloud.githubusercontent.com/assets/45890/12503793/b22f31aa-c112-11e5-9054-8f8b931d89a6.png)

With 0.9 it was showing more settings (like command line to run etc).

**Comment by geksilla** [comment]
this is really strange. Configuration didn't touched for 3 months. I'll check what happened.

**Comment by geksilla** [comment]
issue reported in atom https://github.com/atom/atom/issues/10426

**Comment by geksilla** [comment]
I'll move configurations to package.json and publish new version

**Comment by geksilla** [comment]
@jackcasey I've published new version 0.11.2 should works as well.
