### ISSUE TITLE
environment package VS process.env

### ISSUE THREAD

**Issue by gotjoshua** [geksilla/atom-fuzzy-grep#39]
After reading the readme for atom-fuzzy-grep, i went to install environment package and it says that it is deprecated:

> Please use process.env directly
> A deprecated package that was required prior to https://github.com/atom/atom/pull/12562. Please uninstall this package from your Atom installation(s).

Is atom-fuzzy-grep updated to use process.env directly? 

If yes, then perhaps the readme just needs updating... 
if not, then i guess this is a feature request to remove dependence on a deprecated package.

**Comment by geksilla** [comment]
Hi @gotjoshua, thanks for contribution. Currently this package doesn't use process.env directly and I'm ok to remove `environment` package since it deprecated. If you want to send PR let me know.
Thanks
