### ISSUE TITLE
Question: public API

### ISSUE THREAD

**Issue by dan-weaver** [geksilla/atom-fuzzy-grep#42]
Hi!  I was wondering if this package provided any public api or any way to programmatically interact with the result set.  As far as I can tell it does not.  I would love to be able to take a snap shot of a result set and put it in a text buffer or even into something like atom-narrow.

**Comment by geksilla** [comment]
Hi @dan-weaver, currently there is no provided service for this package. Sorry but I cannot give any estimates when it will be available :cry:

**Comment by dan-weaver** [comment]
@geksilla thanks!  Just wondering.
