### ISSUE TITLE
version 0.17.0 totally doesn't work

### ISSUE THREAD

**Issue by lperson** [geksilla/atom-fuzzy-grep#46]
Hi.  I updated from 0.16.0 to 0.17.0 yesterday.  atom-fuzzy-grep stopped working.  When I say "stopped working" I mean that when I executed Fuzzy Grep: Toggle either with the key combination (alt-ctrl-g) or with the command palette, the text entry field did not appear.  I verified in the Key Binding Resolver that alt-ctrl-g did, in fact, attempt to execute the correct command.

I uninstalled and reinstalled 0.16.0 and it works again.

Thanks for this tool.  It's awesome.

**Comment by wende** [comment]
Same here. Unfortunately, the error message isn't very verbose
<img width="555" alt="screen shot 2017-12-12 at 16 15 40" src="https://user-images.githubusercontent.com/4634386/33891958-cd7bd84a-df57-11e7-9420-9a7de2280575.png">

**Comment by geksilla** [comment]
Hey guys. Sorry for this issue :cry: I just released 0.17.1 it should fix this. Please update package and let me know if it works for you.

**Comment by lperson** [comment]
Thanks for the incredibly rapid turn around!

**Comment by wende** [comment]
Works like a charm! Thanks for sharing this amazing tool 👍

**Comment by geksilla** [comment]
I'm happy that you like it! Huge thanks to @astephenb who provide fix for this issue!
