### ISSUE TITLE
search for ag, but in a git repo it should use git grep, right?

### ISSUE THREAD

**Issue by danielecr** [geksilla/atom-fuzzy-grep#47]
when start typing I have:
> Failed to spawn command ag. Make sure ag is installed and on your PATH

but I expected that it was using git grep?
what does it means "it read from project folder", in my folder project there is .git subfolder, and there are no unstaged changes
linux platform, I can of course install silversearcher-ag, if need, but does it search in git too?

**Comment by geksilla** [comment]
@danielecr thanks for report! It seems like Atom's API was changed a bit so git repo detection doesn't work for now. I will take a look

**Comment by geksilla** [comment]
@danielecr it should work fine in new release. Released 0.17.2, please try to update your package. Let me know if it works for you.

**Comment by danielecr** [comment]
@geksilla it works fine now! Thank you very much for fixing it!
