### ISSUE TITLE
Doesn't escape special characters

### ISSUE THREAD

**Issue by kankaristo** [geksilla/atom-fuzzy-grep#6]
I tried searching for a C++ constructor with `Hierarchy(` and `atom-fuzzy-grep` found nothing. It works fine if I escape the parenthesis (`Hierarchy\(`). `ag` is trying to parse it as a regular expression.

You don't have to escape special characters with `ag --literal`, but this should probably be the default with `atom-fuzzy-grep`?

It would be nice to have a checkbox for toggling regular expressions in the dialog window (could also be toggled with a key binding while the dialog is open).

**Comment by kankaristo** [comment]
Alternatively, allow for multiple grep commands in settings, and a toggle between them in the dialog window?

`ag --literal` should still be the default in my opinion, because people might just think that `atom-fuzzy-grep` is "broken" when it doesn't find anything. It doesn't report an error, unlike `ag` on the command line.

**Comment by geksilla** [comment]
@kankaristo, thanks for report. I will add error handling on described case. Regarding `--literal` flag as default option actually I don't want to enable it by default because of regexp power. You can set any command/flag which useful for you on plugin settings page. Thanks.

**Comment by kankaristo** [comment]
What do you think about having the option to choose between different search commands?

I agree that it would be bad to lose the regex search altogether, but it would be nice to have a drop-down box with different search commands, so you could switch between them without having to go the settings.

This could be a string array in settings and a drop-down box in the search dialog.

**Comment by geksilla** [comment]
I want to keep UI minimal and provide fast interaction with dialog without mouse or redundant key press.
You can add custom script to your `~/.atom/init.coffee` to switch between search command by set `atom-fuzzzy-grep.grepCommandString` to any value you want via some key binding.

**Comment by kankaristo** [comment]
I didn't even think of that option. Thanks! :D

That suggestion could be added to `README.md`, in case someone else wants multiple search commands.

I'll leave this ticket open for now, since `atom-fuzzy-grep` should show an error when the search fails entirely (like with `ag "Hierarchy("`).

**Comment by geksilla** [comment]
@kankaristo, thanks!

**Comment by kankaristo** [comment]
In case someone else wants to have a key binding to change the grep command, here's what I did in `init.coffee`:

``` CoffeeScript
atom.commands.add 'atom-workspace', 'fuzzy-grep:change-search-command', ->
  currentCommand = atom.config.get('atom-fuzzy-grep.grepCommandString')
  commands = [
    'ag -S --nocolor --nogroup --column --literal',
    'ag -S --nocolor --nogroup --column'
  ]
  newCommand = commands[0]
  for command, i in commands
    if command is currentCommand and commands[i + 1]?
      newCommand = commands[i + 1]
      break
  atom.config.set('atom-fuzzy-grep.grepCommandString', newCommand)
  atom.notifications.addInfo(
    "Changed fuzzy-grep search command",
    {detail: newCommand}
  )
```

Then just bind `fuzzy-grep:change-search-command` to something.
